import { Question, typeQuestions } from "./types.d";

export const questionsArray: Question[] = [
  {
    question: "¿Cuál es el elemento químico más abundante en el universo?",
    answers: ["Hidrógeno", "Helio", "Oxígeno", "Carbono"],
    correct: 0,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué planeta es conocido como el planeta rojo?",
    answers: ["Venus", "Júpiter", "Marte", "Saturno"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es la unidad básica de la vida?",
    answers: ["Átomo", "Célula", "Molécula", "Tejido"],
    correct: 1,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué gas necesitan las plantas para realizar la fotosíntesis?",
    answers: ["Oxígeno", "Nitrógeno", "Dióxido de carbono", "Hidrógeno"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es la velocidad de la luz en el vacío?",
    answers: ["300,000 km/s", "150,000 km/s", "200,000 km/s", "250,000 km/s"],
    correct: 0,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué elemento tiene el símbolo químico 'Fe'?",
    answers: ["Flúor", "Hierro", "Fósforo", "Fermio"],
    correct: 1,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es la fórmula química del agua?",
    answers: ["H2O", "CO2", "O2", "H2O2"],
    correct: 0,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué científico propuso la teoría de la relatividad?",
    answers: [
      "Isaac Newton",
      "Niels Bohr",
      "Albert Einstein",
      "Galileo Galilei",
    ],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es el hueso más largo del cuerpo humano?",
    answers: ["Húmero", "Fémur", "Tibia", "Radio"],
    correct: 1,
    type: typeQuestions.SCIENCE,
  },
  {
    question:
      "¿Qué vitamina se produce en la piel cuando nos exponemos al sol?",
    answers: ["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina E"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es el órgano más grande del cuerpo humano?",
    answers: ["Hígado", "Cerebro", "Pulmones", "Piel"],
    correct: 3,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué gas compone mayoritariamente la atmósfera terrestre?",
    answers: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Argón"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es la partícula subatómica con carga positiva?",
    answers: ["Electrón", "Neutrón", "Protón", "Fotón"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question:
      "¿Qué ley de Newton establece que 'a toda acción le corresponde una reacción igual y opuesta'?",
    answers: ["Primera ley", "Segunda ley", "Tercera ley", "Cuarta ley"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question:
      "¿Cuál es el proceso por el cual las plantas fabrican su alimento?",
    answers: ["Respiración", "Fotosíntesis", "Digestión", "Fermentación"],
    correct: 1,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué tipo de radiación tiene la longitud de onda más corta?",
    answers: ["Rayos X", "Luz visible", "Rayos gamma", "Ondas de radio"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es el planeta más grande del sistema solar?",
    answers: ["Tierra", "Saturno", "Júpiter", "Neptuno"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué gas respiran los seres humanos para vivir?",
    answers: ["Dióxido de carbono", "Nitrógeno", "Oxígeno", "Hidrógeno"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es la unidad básica de la herencia?",
    answers: ["Célula", "Cromosoma", "Gen", "ADN"],
    correct: 2,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Qué científico formuló la ley de la gravitación universal?",
    answers: [
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Stephen Hawking",
    ],
    correct: 1,
    type: typeQuestions.SCIENCE,
  },
  {
    question: "¿Cuál es la capital de Afganistán?",
    answers: ["Kabul", "Kandahar", "Herat", "Islamabad"],
    correct: 0,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Albania?",
    answers: ["Durrës", "Vlorë", "Tirana", "Skopie"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Alemania?",
    answers: ["Múnich", "Hamburgo", "Fráncfort", "Berlín"],
    correct: 3,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Andorra?",
    answers: ["Encamp", "Andorra la Vieja", "La Massana", "Tolosa"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Angola?",
    answers: ["Huambo", "Luanda", "Lobito", "Kinsasa"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Arabia Saudita?",
    answers: ["La Meca", "Medina", "Riad", "Yeda"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Argelia?",
    answers: ["Orán", "Constantina", "Argel", "Túnez"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Argentina?",
    answers: ["Córdoba", "Rosario", "Buenos Aires", "Montevideo"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Armenia?",
    answers: ["Giumri", "Ereván", "Vanadzor", "Tiflis"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Australia?",
    answers: ["Sídney", "Melbourne", "Brisbane", "Canberra"],
    correct: 3,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Austria?",
    answers: ["Salzburgo", "Innsbruck", "Viena", "Graz"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Azerbaiyán?",
    answers: ["Ganja", "Sumqayit", "Bakú", "Ereván"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bahamas?",
    answers: ["Freeport", "Nasáu", "West End", "La Habana"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bangladés?",
    answers: ["Chittagong", "Khulna", "Daca", "Calcuta"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Barbados?",
    answers: ["Speightstown", "Oistins", "Bridgetown", "Holetown"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Baréin?",
    answers: ["Manama", "Riffa", "Muharraq", "Doha"],
    correct: 0,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bélgica?",
    answers: ["Amberes", "Gante", "Charleroi", "Bruselas"],
    correct: 3,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Belice?",
    answers: ["Ciudad de Belice", "San Ignacio", "Belmopán", "Orange Walk"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Benín?",
    answers: ["Cotonú", "Porto Novo", "Abomey-Calavi", "Lomé"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bielorrusia?",
    answers: ["Gómel", "Minsk", "Maguilov", "Kiev"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Birmania (Myanmar)?",
    answers: ["Rangún", "Mandalay", "Naipyidó", "Bangkok"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bolivia?",
    answers: ["Santa Cruz", "La Paz", "Sucre", "Cochabamba"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bosnia y Herzegovina?",
    answers: ["Bania Luka", "Mostar", "Sarajevo", "Belgrado"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Botsuana?",
    answers: ["Francistown", "Gaborone", "Molepolole", "Harare"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Brasil?",
    answers: ["Río de Janeiro", "São Paulo", "Salvador", "Brasilia"],
    correct: 3,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Brunéi?",
    answers: ["Kuala Belait", "Seria", "Bandar Seri Begawan", "Kota Kinabalu"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bulgaria?",
    answers: ["Plovdiv", "Varna", "Sofía", "Bucarest"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Burkina Faso?",
    answers: ["Bobo-Dioulasso", "Koudougou", "Uagadugú", "Acra"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Burundi?",
    answers: ["Buyumbura", "Gitega", "Ngozi", "Kigali"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Bután?",
    answers: ["Paro", "Punakha", "Timbu", "Katmandú"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Cabo Verde?",
    answers: ["Mindelo", "Praia", "Santa María", "Dakar"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Camboya?",
    answers: ["Siem Reap", "Battambang", "Phnom Penh", "Bangkok"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Camerún?",
    answers: ["Duala", "Yaundé", "Garoua", "Abuya"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Canadá?",
    answers: ["Toronto", "Montreal", "Vancouver", "Ottawa"],
    correct: 3,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Catar?",
    answers: ["Rayán", "Doha", "Al Wakrah", "Manama"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Chad?",
    answers: ["Moundou", "Sarh", "Yamena", "Niamey"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Chile?",
    answers: ["Valparaíso", "Concepción", "Santiago", "Buenos Aires"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de China?",
    answers: ["Shanghái", "Pekín", "Cantón", "Hong Kong"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Chipre?",
    answers: ["Limassol", "Lárnaca", "Nicosia", "Atenas"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Colombia?",
    answers: ["Medellín", "Cali", "Bogotá", "Caracas"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Comoras?",
    answers: ["Mutsamudu", "Moroni", "Domoni", "Antananarivo"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Corea del Norte?",
    answers: ["Hamhung", "Chongjin", "Pionyang", "Seúl"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Corea del Sur?",
    answers: ["Busan", "Incheon", "Daegu", "Seúl"],
    correct: 3,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Costa de Marfil?",
    answers: ["Abiyán", "Yamusukro", "Bouaké", "Acra"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Costa Rica?",
    answers: ["Limón", "San José", "Alajuela", "Panamá"],
    correct: 1,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Croacia?",
    answers: ["Split", "Rijeka", "Zagreb", "Liubliana"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Cuba?",
    answers: ["Santiago de Cuba", "Camagüey", "La Habana", "Miami"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Dinamarca?",
    answers: ["Aarhus", "Odense", "Copenhague", "Estocolmo"],
    correct: 2,
    type: typeQuestions.GEO,
  },
  {
    question: "¿Cuál es la capital de Yibuti?",
    answers: ["Ali Sabieh", "Tadjoura", "Yibuti", "Adís Abeba"],
    correct: 2,
    type: typeQuestions.GEO,
  },
];

